### ISSUE TITLE
Missing documentation on audio_event_detection model

### ISSUE THREAD

**Issue by YaelBx** [STMicroelectronics/stm32ai-modelzoo#1]
[audio_event_detection](https://github.com/STMicroelectronics/stm32ai-modelzoo/tree/main/audio_event_detection) model is given by ST with models and scripts.
Unlike other model from the repository, there is no getting started documentation on how to setup and how to perform a basic test of the model. (edit, seems like this documentation is in the [scripts](https://github.com/STMicroelectronics/stm32ai-modelzoo/tree/main/audio_event_detection/scripts)/evaluate/ folder. Still, the getting started would be nice)

Could you please add this documentation?

**Comment by YHASTM** [comment]
Hi @YaelBx,

The getting started for audio event detection will be available soon on STM32 model zoo. Stay tuned!
