### ISSUE TITLE
deploy.py from Model Zoo Github does not recognize board nor STM32AI installation

### ISSUE THREAD

**Issue by alamt22** [STMicroelectronics/stm32ai-modelzoo#11]
I have been able to follow all instructions on the "Before you start" section to successfully download the repository and download all requirements. However, I am getting 2 different errors when I run deploy.py.

For context, I was attempting to follow this tutorial: https://github.com/STMicroelectronics/stm32ai-modelzoo/blob/main/object_detection/scripts/deployment/README.md

When I set footprints_on_target to false on the user_config.yaml file in order to benchmark my model using the local download of STM32CubeAI, I get the following error:

![image](https://github.com/STMicroelectronics/stm32ai-modelzoo/assets/15277701/bd85b9fc-e04b-4e9b-993f-f2556a148922)

I have followed every other instruction in the tutorial above, making sure that the paths to the model, cube IDE, and STM32CubeAI are correct. However, deploy.py is unable to recognize the STM32CubeAI despite being given the correct path to the executable. I followed the instructions in the tutorial to unzip both the .zip and .pack files that came with the STM32Cube.AI download. I then used STM32CubeMX to install STM32CubeAI onto my machine, alongside the OS-dependent part of STM32CubeAI. This however did not resolve the error.

Benchmarking and validating my model through Developer Cloud Services (by setting footprints_on_target to STM32H747I-DISCO) works, but when the script then attempts to flash the generated C code onto my board (connected via micro-USB from the ST-Link port), it produces the following error:

![image](https://github.com/STMicroelectronics/stm32ai-modelzoo/assets/15277701/ffea2434-bf91-4a9b-97b2-b36edf06ad9a)

I was wondering how I could resolve both of these issues in the deploy.py script.

**Comment by MDUSTM** [comment]
Hello,

On some boards, the name reported changed that is causing the issue you observed
Board name mismatch
a.	Description: Customer’s board is named “DISCO-H747XI”, whereas the conf file is expecting “STM32H747I-DISCO”. This causes deploy.py to fail. 
b.	Workaround: Change Line 5: "board" name to "DISCO-H747XI" in the file [..\stm32ai-modelzoo\object_detection\getting_started\stmaic_c_project.conf].
 
You may also have an issue with the LCD, on recent boards the LCD also changed :  LCD daughterboard MB1166-A09 uses part number FRD400B25025-A-CTK with the NT35510 driver IC, whereas MB1166-A03 daughterboard uses part number FRD397B25009-D-CTK with driver IC OTM8009A. 

A fix has been published within the STM32H7 Cube package that we are currently adapting for the model zoo application.
