### ISSUE TITLE
Issue with Google Colab code

### ISSUE THREAD

**Issue by AIStudentbl2** [STMicroelectronics/stm32ai-modelzoo#27]
The Google Colab file for the Image Classification model does not have the train.py file:
![Screenshot 2024-03-02 114016](https://github.com/STMicroelectronics/stm32ai-modelzoo/assets/161795229/d0a5393d-1fb8-49b3-9713-7f6228473e61)

**Comment by KBOUSTM** [comment]
Hello,

It seems like you are using an outdated version of the notebook with the latest release of the model zoo. However, a new version of the model zoo is now available, and you can use the updated notebook at https://github.com/STMicroelectronics/stm32ai-modelzoo/blob/main/tutorials/notebooks/stm32ai_model_zoo_colab.ipynb without encountering any issues.

Thank you.
