### ISSUE TITLE
Unable to run Model Zoo onto STM32L562 Board

### ISSUE THREAD

**Issue by AIStudentbl2** [STMicroelectronics/stm32ai-modelzoo#29]
I have connected my STM32L562 board to my computer to connect to the IDE, and I know there is no issue with the cable as my PC will show that the STM is connected (2nd picture), but the IDE is saying that there is no device connected:
![image](https://github.com/STMicroelectronics/stm32ai-modelzoo/assets/161795229/51605f1b-efe4-4587-bae0-adff267d8319)

![image](https://github.com/STMicroelectronics/stm32ai-modelzoo/assets/161795229/bfecfb60-9f74-4c89-b3dd-b88521898c4a)

**Comment by LFOSTM** [comment]
Hello,
This is not a model zoo issue...
Please post your issue here : https://community.st.com/t5/stm32-mcus-machine-learning-ai/bd-p/stm32-mcu-machine-learning-ai-forum
Regards,

**Comment by LFOSTM** [comment]
Hello,
For non related ML questions, but related to Cube IDE, , you can post your questions here : https://community.st.com/t5/stm32cubeide-mcus/bd-p/stm32-mcu-cubeide-forum
Thanks,
