### ISSUE TITLE
Is it possible to use several onnx models in the board?

### ISSUE THREAD

**Issue by jozapa** [STMicroelectronics/stm32ai-modelzoo#31]
I have 3 .onnx models that works for different things in my project. The idea is to upload the 3 models to the board. I don´t know how to do that because you only can put one model in the "model_path".
Thanks!!

**Comment by GRATTINSTM** [comment]
Hello @jozapa, 

Which use case are you using? 
The ModelZoo doesn't support multi models applications. If possible, you may find a way to merge the three models into one using a high level API and then upload the resulting model. 

Guillaume
