### ISSUE TITLE
Question: Is STM32H745XIH6 micro-controller suitable for running object detection models?

### ISSUE THREAD

**Issue by MohamedElhadidy0019** [STMicroelectronics/stm32ai-modelzoo#32]
From your README I have understood that the Disco board is capable of running object detection models, but does the microcontroller itself of the board be able to run the models standalone?

**Comment by LFOSTM** [comment]
Hello,
It depends on the model size, but if no external memory is needed, the model should be capable of running on this device. STM32H745XIH6 is not part of the developer cloud. Maybe you can make a try on one of the device on the ST developer cloud with features close to the one you use.
Regards,
