### ISSUE TITLE
B cam omv + USB Display

### ISSUE THREAD

**Issue by Vietsol-AnhHaiLe** [STMicroelectronics/stm32ai-modelzoo#37]
hello,

I have issue when i ran example image classsification for stm32h743zi2

my error is 
![image](https://github.com/STMicroelectronics/stm32ai-modelzoo/assets/166009574/d2f3f118-a3dd-423c-af44-bae64acbaa19)
 can you help me, tks alot

**Comment by Vietsol-AnhHaiLe** [comment]
Hello,

Im trying stm32-Model zoo examples but i have some problems

Image classification - FdMobilenet : I have generated code from image_classification.ipynb and flash the program success

But after i flash, my hardware seem get in to loop that can't find camera init, i have checked wires for many times and it works well, but my board NUCLEO-H743ZI2  + B-Cam OMV + USB Display stop at welcome screen

Can you help me!

Thanks

________________________________

**Comment by Vietsol-AnhHaiLe** [comment]
can you record a short video about your live project please
________________________________

**Comment by Vietsol-AnhHaiLe** [comment]
my generate success but it doesn't work
[cid:d309dc56-2b06-40f1-8bf3-062626153774]

[cid:426c92d4-e50f-4294-a53d-a601aae78181]
________________________________

**Comment by Vietsol-AnhHaiLe** [comment]
![image](https://github.com/STMicroelectronics/stm32ai-modelzoo/assets/166009574/6cef3d35-8023-4d01-b6ef-de136542cd0c)
![image](https://github.com/STMicroelectronics/stm32ai-modelzoo/assets/166009574/85a499e5-ef86-4732-8ad5-d8fdc6a6eb4a)

**Comment by Vietsol-AnhHaiLe** [comment]
![image](https://github.com/STMicroelectronics/stm32ai-modelzoo/assets/166009574/261f6f6e-a491-42dc-8054-291b501124a1)

**Comment by GRATTINSTM** [comment]
Please find attached the project I tested on my NUCLEO-H743ZI2 and working as expected. 
[image_classification.zip](https://github.com/user-attachments/files/15886526/image_classification.zip)

Guillaume

**Comment by Vietsol-AnhHaiLe** [comment]
Hello @***@***.***>, Im trying STM32F746G_Discovery + B-CAM-OMVS => Image classification

Im a student and im interested in Image CLassification on Hardware and im trying to using it á an sample for my final Uni projects but i dont have much experience on Hardware, coud your team please doing a samples project with my hardware, tks a lot

________________________________
